version: '3'
services:

  reservation-db:
    image: postgres:13.1
    container_name: reservation-db
    environment:
      POSTGRES_DB: reservation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5441:5432"
    volumes:
      - reservation-volume:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    ports:
      - "8888:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev" ]
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data

volumes:
  reservation-volume:
  keycloak-data:
