version: '3'
services:
  reservation-db:
    image: postgres:13.1
    container_name: eticket-reservation-db
    environment:
      POSTGRES_DB: eticket-reservation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5441:5432"
    volumes:
      - eticket-reservation-volume:/var/lib/postgresql/data
volumes:
  eticket-reservation-volume:
